<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Characters\Traits\Core\NpcTraitInitializer.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="AI\Brain\Legacy\Brain.cs.disabled" />
    <None Remove="AI\Brain\Legacy\DialogueEngine.cs.disabled" />
    <None Remove="AI\Brain\Legacy\ThoughtEngine.cs.disabled" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LM-Kit.NET" Version="2026.8.1" />
    <PackageReference Include="LM-Kit.NET.Backend.Cuda12.Windows" Version="2026.8.1" />

    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />

    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />

    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ProjectEve.Core\ProjectEve.Core\ProjectEve.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="AI\Brain\Legacy\" />
    <Folder Include="Characters\Traits\TraitJson\Matrix\" />
    <Folder Include="Characters\Traits\TraitJson\SubSlowTraits\" />
    <Folder Include="Characters\Traits\TraitJson\MidTraits\" />
    <Folder Include="Characters\Traits\TraitJson\TraitHistory\" />
  </ItemGroup>

</Project>
