using System.Text.RegularExpressions;

namespace ProjectEve.NpcStudio.Services;

/// <summary>
/// Central filesystem authority for NPC media generated by NPC Studio.
/// School and family media stay separated on disk while both may reference
/// the same canonical NPC through database media records.
/// </summary>
public sealed class MediaStorageService
{
    public const string MediaRoot = @"D:\ProjectEveData\Media";
    public const string SchoolSystemRoot = @"D:\ProjectEveData\Media\SchoolSystem";
    public const string FamiliesRoot = @"D:\ProjectEveData\Media\Families";

    public MediaStorageService()
    {
        EnsureFoundation();
    }

    public void EnsureFoundation()
    {
        Directory.CreateDirectory(MediaRoot);
        Directory.CreateDirectory(SchoolSystemRoot);
        Directory.CreateDirectory(FamiliesRoot);

        foreach (var school in new[] { "BHS", "BMS", "BIS", "BES" })
        {
            Directory.CreateDirectory(Path.Combine(SchoolSystemRoot, "Schools", school, "staff"));
            Directory.CreateDirectory(Path.Combine(SchoolSystemRoot, "Schools", school, "students"));
        }

        Directory.CreateDirectory(Path.Combine(
            SchoolSystemRoot,
            "District",
            "BellefontaineCitySchools",
            "branding"));

        Directory.CreateDirectory(Path.Combine(
            SchoolSystemRoot,
            "District",
            "BellefontaineCitySchools",
            "buildings"));

        Directory.CreateDirectory(Path.Combine(
            SchoolSystemRoot,
            "District",
            "BellefontaineCitySchools",
            "events"));
    }

    public string EnsureSchoolStaffNpcFolder(string schoolCode, long npcId)
    {
        var root = Path.Combine(
            SchoolSystemRoot,
            "Schools",
            SanitizeSegment(schoolCode),
            "staff",
            NpcFolderName(npcId));

        CreateNpcMediaFolders(root, includeSchoolFolder: false);
        Directory.CreateDirectory(Path.Combine(root, "work"));
        return root;
    }

    public string EnsureSchoolStudentNpcFolder(string schoolCode, long npcId)
    {
        var root = Path.Combine(
            SchoolSystemRoot,
            "Schools",
            SanitizeSegment(schoolCode),
            "students",
            NpcFolderName(npcId));

        CreateNpcMediaFolders(root, includeSchoolFolder: true);
        return root;
    }

    public string EnsureHouseholdFolder(long householdId)
    {
        var root = Path.Combine(FamiliesRoot, $"Household_{householdId:D6}");

        Directory.CreateDirectory(root);
        Directory.CreateDirectory(Path.Combine(root, "family"));
        Directory.CreateDirectory(Path.Combine(root, "family", "group"));
        Directory.CreateDirectory(Path.Combine(root, "family", "home"));
        Directory.CreateDirectory(Path.Combine(root, "family", "events"));

        return root;
    }

    public string EnsureFamilyNpcFolder(long householdId, long npcId, bool schoolAge)
    {
        var householdRoot = EnsureHouseholdFolder(householdId);
        var root = Path.Combine(householdRoot, NpcFolderName(npcId));

        CreateNpcMediaFolders(root, includeSchoolFolder: schoolAge);
        return root;
    }

    public string GetPrimaryProfilePath(
        string contextRoot,
        long npcId,
        string extension = ".png")
    {
        extension = NormalizeExtension(extension);
        var profileFolder = Path.Combine(contextRoot, "profile");
        Directory.CreateDirectory(profileFolder);

        return Path.Combine(
            profileFolder,
            $"NPC_{npcId:D6}_primary{extension}");
    }

    public string GetProfessionalProfilePath(
        string schoolCode,
        long npcId,
        string extension = ".png")
    {
        extension = NormalizeExtension(extension);
        var root = EnsureSchoolStaffNpcFolder(schoolCode, npcId);
        var profileFolder = Path.Combine(root, "profile");

        return Path.Combine(
            profileFolder,
            $"NPC_{npcId:D6}_professional{extension}");
    }

    public string GetSchoolProfilePath(
        string schoolCode,
        long npcId,
        string extension = ".png")
    {
        extension = NormalizeExtension(extension);
        var root = EnsureSchoolStudentNpcFolder(schoolCode, npcId);
        var schoolFolder = Path.Combine(root, "school");

        return Path.Combine(
            schoolFolder,
            $"NPC_{npcId:D6}_school{extension}");
    }

    private static void CreateNpcMediaFolders(string root, bool includeSchoolFolder)
    {
        Directory.CreateDirectory(root);
        Directory.CreateDirectory(Path.Combine(root, "profile"));
        Directory.CreateDirectory(Path.Combine(root, "casual"));
        Directory.CreateDirectory(Path.Combine(root, "social"));
        Directory.CreateDirectory(Path.Combine(root, "historical"));

        if (includeSchoolFolder)
        {
            Directory.CreateDirectory(Path.Combine(root, "school"));
        }
    }

    private static string NpcFolderName(long npcId) => $"NPC_{npcId:D6}";

    private static string NormalizeExtension(string extension)
    {
        if (string.IsNullOrWhiteSpace(extension))
        {
            return ".png";
        }

        return extension.StartsWith('.') ? extension : "." + extension;
    }

    private static string SanitizeSegment(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            throw new ArgumentException("Folder segment cannot be empty.", nameof(value));
        }

        var invalidChars = Regex.Escape(new string(Path.GetInvalidFileNameChars()));
        var invalid = new Regex($"[{invalidChars}]");
        return invalid.Replace(value.Trim(), "_");
    }
}
